name: sharik_wrapper
description: Wrapper for sharik
version: 0.0.1
author: marchellodev
homepage: marchello.cf

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: dev.marchello.sharik_wrapper
        pluginClass: SharikWrapperPlugin
      ios:
        pluginClass: SharikWrapperPlugin
      macos:
        pluginClass: SharikWrapperPlugin
