// Objective-C API for talking to github.com/marchellodev/sharic/wrapper Go package.
//   gobind -lang=objc github.com/marchellodev/sharic/wrapper
//
// File is generated by gobind. Do not edit.

#ifndef __Wrapper_H__
#define __Wrapper_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull WrapperGetIp(void);

#endif
