
// Objective-C API for talking to the following Go packages
//
//	github.com/marchellodev/sharic/wrapper
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Wrapper_FRAMEWORK_H__
#define __Wrapper_FRAMEWORK_H__

#include "Wrapper.objc.h"
#include "Universe.objc.h"

#endif
